import{a as y,i as a,S as p}from"./assets/vendor-mdVVRe9K.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function c(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=c(t);fetch(t.href,s)}})();const b="45718127-30771d56f6b088ceef33bd7c7",L="https://pixabay.com/api/";async function f(e,r=1){try{return(await y.get(L,{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch{throw new Error("Failed to fetch images")}}function h(e){const r=document.querySelector(".gallery"),c=e.map(o=>`
            <a href="${o.largeImageURL}" class="gallery__link">
                <div class="gallery-item">
                    <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
                    <div class="info">
                        <p class="info-item"><b>Likes</b> ${o.likes}</p>
                        <p class="info-item"><b>Views</b> ${o.views}</p>
                        <p class="info-item"><b>Comments</b> ${o.comments}</p>
                        <p class="info-item"><b>Downloads</b> ${o.downloads}</p>
                    </div>
                </div>
            </a>
        `).join("");r.insertAdjacentHTML("beforeend",c)}const w=document.querySelector("#search-form"),g=document.querySelector(".gallery"),n=document.querySelector(".load-more-btn");let l="",i=1,m=0,d;w.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.currentTarget.elements.user_query.value.trim(),l===""){a.error({title:"Error",message:"Please enter a search query"});return}i=1,g.innerHTML="";try{const r=await f(l,i);if(m=r.totalHits,r.hits.length===0){a.warning({title:"No results",message:"Sorry, there are no images matching your search query."}),n.classList.add("is-hidden");return}h(r.hits),d=new p(".gallery a"),d.refresh(),n.classList.remove("is-hidden")}catch(r){a.error({title:"Error",message:r.message})}});n.addEventListener("click",async()=>{i+=1;try{const e=await f(l,i);if(e.hits.length===0||i*15>=m){a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}),n.classList.add("is-hidden");return}h(e.hits),d.refresh()}catch(e){a.error({title:"Error",message:e.message})}});n.addEventListener("click",async()=>{i+=1;try{const e=await f(l,i);if(e.hits.length===0||i*15>=m){a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}),n.classList.add("is-hidden");return}h(e.hits),d.refresh();const{height:r}=g.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch(e){a.error({title:"Error",message:e.message})}});
//# sourceMappingURL=index.js.map
